### PR TITLE
use Buffer.compare if it exists

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by soldair** [comment]
hi. Thanks! 
It looks like `a` and `b` are undefined. if you could update the pr to use `cmp.compare(to)` it would work great i bet.

**Comment by soldair** [comment]
i see this is supposed to follow the first ;)

**Comment by soldair** [comment]
mind resolving this for me?

**Comment by soldair** [comment]
never mind =) released it all as v1.1.0

**Comment by dcousens** [comment]
Cheers :+1:

**Pull request merged**
